---
- import_playbook: prov_db.yml
- import_playbook: prov_app.yml


# - name: Gather DB Host IP
#   hosts: db
#   gather_facts: yes
#   tasks:
#     - name: Set db_host_ip fact
#       set_fact:
#         db_host_ip: "{{ ansible_default_ipv4.address }}"

# - name: Distribute db_host_ip to Web Hosts
#   hosts: web
#   gather_facts: no
#   tasks:
#     - name: Set db_host_ip fact for web hosts
#       set_fact:
#         db_host_ip: "{{ hostvars[groups['db'][0]]['db_host_ip'] }}"

# ---
# - name: Provision NodeJS application with pm2
#   hosts: web
#   become: true
#   gather_facts: yes
#   vars:
#     db_host_ip: "{{ db_host_ip }}"

#   tasks:
#     # Add NodeSource repository for Node.js 20.x
#     - name: Run NodeSource setup script for Node.js 20.x
#       ansible.builtin.shell: "curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -"

#     # Install NodeJS 20.x
#     - name: Install NodeJS 20
#       ansible.builtin.apt:
#         name: nodejs
#         state: present
#       tags: install_node

#     - name: Install npm explicitly
#       ansible.builtin.apt:
#         name: npm
#         state: present

#     - name: Clone the app repository to the control node
#       delegate_to: localhost
#       ansible.builtin.git:
#         repo: 'https://github.com/AdonisAlgos/tech264-sparta-app.git'
#         dest: /home/ubuntu/repo
#         version: main
#       tags: clone_app

#     # Copy the 'app' folder to the target node
#     - name: Copy app folder to target node
#       ansible.builtin.copy:
#         src: /home/ubuntu/repo/
#         dest: /home/ubuntu/
#         mode: '0755'
#       tags: copy_app

#     # Install dependencies with npm
#     - name: Install dependencies with npm
#       ansible.builtin.shell:
#         cmd: npm install
#         chdir: /home/ubuntu/app
#       tags: npm_install

#     - name: Add DB_HOST environment variable to /etc/environment (persistent)
#       ansible.builtin.lineinfile:
#         path: /etc/environment
#         line: 'DB_HOST=mongodb://{{ db_host_ip }}:27017/posts'
#         state: present

#     # Install pm2 globally
#     - name: Install pm2 globally
#       ansible.builtin.shell:
#         cmd: npm install -g pm2
#       tags: install_pm2

#     # Stop pm2 processes
#     - name: Stop all processes running on pm2
#       ansible.builtin.shell:
#         cmd: pm2 stop all
#         chdir: /home/ubuntu/app
#       tags: pm2_stop

#     # Start the application with pm2, setting environment variable
#     - name: Start the application with pm2
#       ansible.builtin.shell:
#         cmd: pm2 start app.js --update-env
#         chdir: /home/ubuntu/app
#       environment:
#         DB_HOST: "mongodb://{{ db_host_ip }}:27017/posts"
#       tags: pm2_start